datadog:
  api_key: '/opt/app/secrets/DD_API_KEY'
  app_name: '/opt/app/secrets/DD_APP_NAME'

inspectlet:
  wid: '/opt/app/secrets/INSPECTLET_KEY'

mailer:
  defaultEmail: '/opt/app/secrets/DEFAULT_EMAIL'
  defaultEmailName: '/opt/app/secrets/DEFAULT_EMAIL_NAME'
  forgetPasswordMailTemplateId: '/opt/app/secrets/FORGOT_PASSWORD_MAIL_TEMPLATE_ID'


mongoDb:
  uri: '/opt/app/secrets/MONGODB_URI'


openai:
  apiKey: '/opt/app/secrets/OPENAI_API_KEY'


otp:
  defaultOTP: '/opt/app/secrets/DEFAULT_OTP'
  defaultPhoneNumber: '/opt/app/secrets/DEFAULT_PHONE_NUMBER'

sendgrid:
  apiKey: '/opt/app/secrets/SENDGRID_API_KEY'
