name: cleanup_pr

on:
  pull_request_target:
    types: [closed]

jobs:
  clean:
    uses: jalantechnologies/github-ci/.github/workflows/clean.yml@1e27a09243327a4ed01d42a9bc54965436ac0ba4
    concurrency:
      group: ci-preview-${{ github.event.pull_request.head.ref }}
      cancel-in-progress: true
    with:
      app_name: node-react-template
      app_env: preview
      branch: ${{ github.event.pull_request.head.ref }}
      docker_registry: ${{ vars.DOCKER_REGISTRY }}
      docker_username: ${{ vars.DOCKER_USERNAME }}
      do_cluster_id: ${{ vars.DO_CLUSTER_ID }}
    secrets:
      docker_password: ${{ secrets.DOCKER_PASSWORD }}
      do_access_token: ${{ secrets.DO_ACCESS_TOKEN }}
