name: cleanup_pr

on:
  pull_request_target:
    types: [closed]

# Ensures PR cleanup workflow has minimal permissions for security
permissions:
  contents: read        # Read-only access to repo contents for safer workflows
  pull-requests: write  # Allow workflow to comment on, label, and update pull request as part of automation
  id-token: write       # Allow OIDC tokens for secure cloud authentication

jobs:
  clean:
    uses: jalantechnologies/github-ci/.github/workflows/clean.yml@fad88356620fd16b87d7aef8fe909917eeaf7f19
    concurrency:
      group: ci-preview-pr-${{ github.event.pull_request.number }}
      cancel-in-progress: true
    with:
      app_name: node-react-template
      app_env: preview
      branch: pr-${{ github.event.pull_request.number }}
      docker_registry: ${{ vars.DOCKER_REGISTRY }}
      docker_username: ${{ vars.DOCKER_USERNAME }}
      do_cluster_id: ${{ vars.DO_CLUSTER_ID }}
    secrets:
      docker_password: ${{ secrets.DOCKER_PASSWORD }}
      do_access_token: ${{ secrets.DO_ACCESS_TOKEN }}
