name: Production Deployment

on:
  push:
    branches:
      - main

jobs:
  production:
    uses: jalantechnologies/github-ci/.github/workflows/ci.yml@v2.5
    concurrency:
      group: ci-production-${{ github.event.ref }}
      cancel-in-progress: true
    with:
      app_name: node-react-template
      app_env: production
      app_hostname: node-react-template.platform.bettrhq.com
      branch: ${{ github.event.ref }}
      docker_registry: ${{ vars.DOCKER_REGISTRY }}
      docker_username: ${{ vars.DOCKER_USERNAME }}
      sonar_host_url: ${{ vars.SONAR_HOST_URL }}
      do_cluster_id: ${{ vars.DO_CLUSTER_ID }}
    secrets:
      docker_password: ${{ secrets.DOCKER_PASSWORD }}
      doppler_token: ${{ secrets.DOPPLER_PRODUCTION_TOKEN }}
      do_access_token: ${{ secrets.DO_ACCESS_TOKEN }}
      sonar_token: ${{ secrets.SONAR_TOKEN }}
